version: '3.9'
services:
    gogrepoc:
        image: leberschnitzel/gogrepocdock:latest
        volumes:
            - ./Downloads:/gogrepocdock/downloads
        environment:
            - goguser=your_gog_username #Your GOG Username (required).
            - gogpassword=your_gog_password #Your GOG Password (required).
            - updatecommands=-os windows linux -lang en #Configuration for update commands. See https://github.com/Kalanyr/gogrepoc for information (required).
            - downloadcommands=-dryrun #Configuration for download commands (optional). Remove -dryrun when you're ready to start actual downloads (optional).
            - repeat=1w #Interval for syncing. Use formats like 1w for 1 week or 3d for 3 days Default is 1w (optional)