version: '3.9'
services:
    gogrepoc:
        image: leberschnitzel/gogrepocdock:latest
        volumes:
            - ./Downloads:/gogrepocdock/downloads #first path should be the folder where you want the downloads to end up
        environment:
            - goguser= #your GOG Username goes here. Required.
            - gogpassword= #Your GOG Password goes here. Required.
            - updatecommands=-os windows linux -lang en #configure as you like. Configure here, not in downloadcommands (I'm working on it).
            - downloadcommands=-dryrun #remove -dryrun once you are sure you want to download.
            - repeat=1w #Repeats the sync every day (d) or week (w). Standard: 1w